// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AIProgrammingAssistant
{
    internal sealed partial class Vsix
    {
        public const string Id = "AIProgrammingAssistant.46850645-4d88-4573-918d-9a8f756b778c";
        public const string Name = "AIProgrammingAssistant";
        public const string Description = @"An AI assistant extension, what help you in coding with the power of GPT langugage models.
OpenAI API key needed";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Zoltán Kende";
        public const string Tags = "";
    }
}
