// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AIProgrammingAssistant
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AIProgrammingAssistantString = "96cf927e-c19e-408d-a951-2020a7ee3542";
        public static Guid AIProgrammingAssistant = new Guid(AIProgrammingAssistantString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0011;
        public const int MyCommandId = 0x0111;
        public const int AIMenuGroup = 0x0001;
        public const int AISubMenu = 0x1100;
        public const int AISubMenuGroup = 0x1150;
        public const int GiveFeedback = 0x1200;
        public const int SuggestVariableNames = 0x1300;
        public const int GenerateTest = 0x0100;
        public const int Optimize = 0x0010;
        public const int CreateQuery = 0x0110;
    }
}